/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'ssd1306' 
 * Target:  'Target 1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device&Standalone:STM32Cube HAL:COMMON@1.12.2 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
