/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'ssd1306' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l0xx.h"

/* Keil::Device&Standalone:STM32Cube HAL:COMMON@1.12.2 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device&Standalone:STM32Cube HAL:CORTEX@1.12.2 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device&Standalone:STM32Cube HAL:DMA@1.12.2 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device&Standalone:STM32Cube HAL:FLASH@1.12.2 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device&Standalone:STM32Cube HAL:GPIO@1.12.2 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device&Standalone:STM32Cube HAL:I2C@1.12.2 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device&Standalone:STM32Cube HAL:PWR@1.12.2 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device&Standalone:STM32Cube HAL:RCC@1.12.2 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device&Standalone:Startup@1.12.2 */
#define RTE_DEVICE_STARTUP_STM32L0XX    /* Device Startup for STM32L0 */


#endif /* RTE_COMPONENTS_H */
